/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Collector } from "@boundaryml/baml"
import { toBamlError } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {EPpair, Entity, EntityExtractionExample, EntityMatch, EntityMatchResult, EntityWithRef, HyDE_rewrite_query, HypothesizedProperty, MissingEntityExtractionResult, Property, PropertyGenerateRes, Relation, RelationExtractResult, RelationGroup, RelationReference, RetrievedDocument, RetrievedPropertyInfo, SummarizedProperty, UpdatedSummary} from "./types"
import type TypeBuilder from "./type_builder"

export class LlmResponseParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  BaselineRAGRetrieveProperty(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): RetrievedPropertyInfo {
    try {
      return this.runtime.parseLlmResponse(
        "BaselineRAGRetrieveProperty",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as RetrievedPropertyInfo
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ConvertQueryToEP(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): string[] {
    try {
      return this.runtime.parseLlmResponse(
        "ConvertQueryToEP",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as string[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DefineEntityWithReferences(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): EntityWithRef {
    try {
      return this.runtime.parseLlmResponse(
        "DefineEntityWithReferences",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as EntityWithRef
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEP(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): EPpair[] {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractEP",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as EPpair[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEntity(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Entity[] {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractEntity",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as Entity[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEntityFromQuery(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Entity[] {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractEntityFromQuery",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as Entity[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEntityLoop(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Entity[] {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractEntityLoop",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as Entity[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractMissingEntities(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): MissingEntityExtractionResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractMissingEntities",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as MissingEntityExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  Extract_relations(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): RelationExtractResult[] {
    try {
      return this.runtime.parseLlmResponse(
        "Extract_relations",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as RelationExtractResult[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  Extract_relations_Loop(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Relation[] {
    try {
      return this.runtime.parseLlmResponse(
        "Extract_relations_Loop",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as Relation[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateAnswer(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): string {
    try {
      return this.runtime.parseLlmResponse(
        "GenerateAnswer",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as string
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateProperty(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): PropertyGenerateRes {
    try {
      return this.runtime.parseLlmResponse(
        "GenerateProperty",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as PropertyGenerateRes
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GroupRelations(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): RelationGroup[] {
    try {
      return this.runtime.parseLlmResponse(
        "GroupRelations",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as RelationGroup[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HyDEDefineEntity(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Entity {
    try {
      return this.runtime.parseLlmResponse(
        "HyDEDefineEntity",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as Entity
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HyDEHypothesizeProperty(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): HypothesizedProperty {
    try {
      return this.runtime.parseLlmResponse(
        "HyDEHypothesizeProperty",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as HypothesizedProperty
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HyDE_rewrite(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): HyDE_rewrite_query {
    try {
      return this.runtime.parseLlmResponse(
        "HyDE_rewrite",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as HyDE_rewrite_query
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  MergeEntities(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): string {
    try {
      return this.runtime.parseLlmResponse(
        "MergeEntities",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as string
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SelectMostMatchingEntity(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): EntityMatch {
    try {
      return this.runtime.parseLlmResponse(
        "SelectMostMatchingEntity",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as EntityMatch
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeProperty(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): SummarizedProperty {
    try {
      return this.runtime.parseLlmResponse(
        "SummarizeProperty",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as SummarizedProperty
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeRelations(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): string {
    try {
      return this.runtime.parseLlmResponse(
        "SummarizeRelations",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as string
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  UpdateSummary(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): UpdatedSummary {
    try {
      return this.runtime.parseLlmResponse(
        "UpdateSummary",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as UpdatedSummary
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  VerifyEntities(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): EntityMatchResult {
    try {
      return this.runtime.parseLlmResponse(
        "VerifyEntities",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as EntityMatchResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class LlmStreamParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  BaselineRAGRetrieveProperty(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.RetrievedPropertyInfo {
    try {
      return this.runtime.parseLlmResponse(
        "BaselineRAGRetrieveProperty",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.RetrievedPropertyInfo
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ConvertQueryToEP(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (string | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "ConvertQueryToEP",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (string | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  DefineEntityWithReferences(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.EntityWithRef {
    try {
      return this.runtime.parseLlmResponse(
        "DefineEntityWithReferences",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.EntityWithRef
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEP(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (partial_types.EPpair | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractEP",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (partial_types.EPpair | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEntity(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (partial_types.Entity | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractEntity",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (partial_types.Entity | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEntityFromQuery(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (partial_types.Entity | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractEntityFromQuery",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (partial_types.Entity | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEntityLoop(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (partial_types.Entity | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractEntityLoop",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (partial_types.Entity | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractMissingEntities(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.MissingEntityExtractionResult {
    try {
      return this.runtime.parseLlmResponse(
        "ExtractMissingEntities",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.MissingEntityExtractionResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  Extract_relations(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (partial_types.RelationExtractResult | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "Extract_relations",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (partial_types.RelationExtractResult | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  Extract_relations_Loop(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (partial_types.Relation | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "Extract_relations_Loop",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (partial_types.Relation | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateAnswer(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): string {
    try {
      return this.runtime.parseLlmResponse(
        "GenerateAnswer",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as string
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateProperty(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.PropertyGenerateRes {
    try {
      return this.runtime.parseLlmResponse(
        "GenerateProperty",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.PropertyGenerateRes
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GroupRelations(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (partial_types.RelationGroup | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "GroupRelations",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (partial_types.RelationGroup | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HyDEDefineEntity(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.Entity {
    try {
      return this.runtime.parseLlmResponse(
        "HyDEDefineEntity",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.Entity
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HyDEHypothesizeProperty(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.HypothesizedProperty {
    try {
      return this.runtime.parseLlmResponse(
        "HyDEHypothesizeProperty",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.HypothesizedProperty
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HyDE_rewrite(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.HyDE_rewrite_query {
    try {
      return this.runtime.parseLlmResponse(
        "HyDE_rewrite",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.HyDE_rewrite_query
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  MergeEntities(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): string {
    try {
      return this.runtime.parseLlmResponse(
        "MergeEntities",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as string
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SelectMostMatchingEntity(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.EntityMatch {
    try {
      return this.runtime.parseLlmResponse(
        "SelectMostMatchingEntity",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.EntityMatch
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeProperty(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.SummarizedProperty {
    try {
      return this.runtime.parseLlmResponse(
        "SummarizeProperty",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.SummarizedProperty
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeRelations(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): string {
    try {
      return this.runtime.parseLlmResponse(
        "SummarizeRelations",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as string
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  UpdateSummary(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.UpdatedSummary {
    try {
      return this.runtime.parseLlmResponse(
        "UpdateSummary",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.UpdatedSummary
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  VerifyEntities(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): partial_types.EntityMatchResult {
    try {
      return this.runtime.parseLlmResponse(
        "VerifyEntities",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as partial_types.EntityMatchResult
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}