/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  Entity,  EntityExtractionExample,  HyDE_rewrite_query,  Relation,  RelationGroup,  RetrievedDocument } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface Entity {
        name?: (string | null)
        description?: (string | null)
        type?: (string | null)
    }
    
    export interface EntityExtractionExample {
        entity_type?: (string | null)[]
        example_input?: (string | null)
        extracted_entities?: (partial_types.Entity | null)[]
    }
    
    export interface HyDE_rewrite_query {
        HyDE_answer?: (string | null)
    }
    
    export interface Relation {
        source_entity?: (string | null)
        target_entity?: (string | null)
        relation?: (string | null)
    }
    
    export interface RelationGroup {
        group_name?: (string | null)
        relation_index?: (number | null)[]
        Reasoning?: (string | null)
    }
    
    export interface RetrievedDocument {
        content?: (string | null)
        metadata?: (string | null)
    }
    
}