/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  Attribute,  EPpair,  Entity,  EntityExtractionExample,  EntityMatch,  EntityMatchResult,  EntityWithRef,  HyDE_rewrite_query,  HypothesizedProperty,  MissingEntityExtractionResult,  Property,  PropertyGenerateRes,  Relation,  RelationExtractResult,  RelationGroup,  RelationReference,  RetrievedDocument,  RetrievedPropertyInfo,  SummarizedProperty,  UpdatedSummary } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface Attribute {
        name?: (string | null)
        description?: (string | null)
        type?: (string | null)
    }
    
    export interface EPpair {
        entity?: (string | null)
        property?: (string | null)
    }
    
    export interface Entity {
        name?: (string | null)
        description?: (string | null)
        type?: (string | null)
        aliases?: (string | null)[]
    }
    
    export interface EntityExtractionExample {
        entity_type?: (string | null)[]
        example_input?: (string | null)
        extracted_entities?: (partial_types.Entity | null)[]
    }
    
    export interface EntityMatch {
        entity?: (string | null)
        confidence?: (number | null)
    }
    
    export interface EntityMatchResult {
        entity_name?: (string | null)
        is_match?: (boolean | null)
        matched_entity_name?: (string | null)
        reasoning?: (string | null)
    }
    
    export interface EntityWithRef {
        name?: (string | null)
        description?: (string | null)
        type?: (string | null)
        aliases?: (string | null)[]
        reference?: (number | null)[]
    }
    
    export interface HyDE_rewrite_query {
        HyDE_answer?: (string | null)
    }
    
    export interface HypothesizedProperty {
        hypothesis?: (string | null)
    }
    
    export interface MissingEntityExtractionResult {
        extracted_entities?: (partial_types.Entity | null)[]
        reasoning?: (string | null)
    }
    
    export interface Property {
        prop_name?: (string | null)
        content?: (string | null)
    }
    
    export interface PropertyGenerateRes {
        content?: (string | null)
        referenceIndex?: (number | null)[]
    }
    
    export interface Relation {
        source_entity?: (string | null)
        target_entity?: (string | null)
        relation?: (string | null)
    }
    
    export interface RelationExtractResult {
        source_entity?: (number | null)
        target_entity?: (number | null)
        relation?: (string | null)
    }
    
    export interface RelationGroup {
        group_name?: (string | null)
        relation_index?: (number | null)[]
        Reasoning?: (string | null)
    }
    
    export interface RelationReference {
        relation?: (partial_types.Relation | null)
        doucment?: (string | null)[]
    }
    
    export interface RetrievedDocument {
        content?: (string | null)
        metadata?: (string | null)
    }
    
    export interface RetrievedPropertyInfo {
        information?: (string | null)
        sources?: (string | null)[]
    }
    
    export interface SummarizedProperty {
        summary?: (string | null)
    }
    
    export interface UpdatedSummary {
        summary?: (string | null)
        changes?: (string | null)[]
    }
    
}