/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio } from "@boundaryml/baml"
import { toBamlError, HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {Entity, EntityExtractionExample, HyDE_rewrite_query, Property, Relation, RelationGroup, RelationReference, RetrievedDocument} from "./types"
import type TypeBuilder from "./type_builder"

type BamlCallOptions = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
}

export class HttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  ExtractEntity(
      chunk_text: string,entity_type: string[],
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "ExtractEntity",
        {
          "chunk_text": chunk_text,"entity_type": entity_type
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEntityFromQuery(
      arg: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "ExtractEntityFromQuery",
        {
          "arg": arg
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEntityLoop(
      chunk_text: string,entity_type: string[],already_identified_entities: Entity[],already_identified_relations: Relation[],
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "ExtractEntityLoop",
        {
          "chunk_text": chunk_text,"entity_type": entity_type,"already_identified_entities": already_identified_entities,"already_identified_relations": already_identified_relations
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  Extract_relations(
      content: string,entities: Entity[],language: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "Extract_relations",
        {
          "content": content,"entities": entities,"language": language
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  Extract_relations_Loop(
      content: string,language: string,already_identified_relations: Relation[],new_indentified_entities: Entity[],
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "Extract_relations_Loop",
        {
          "content": content,"language": language,"already_identified_relations": already_identified_relations,"new_indentified_entities": new_indentified_entities
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateAnswer(
      query: string,documents: RetrievedDocument[],language: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "GenerateAnswer",
        {
          "query": query,"documents": documents,"language": language
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GroupRelations(
      core_entity: Entity,relations: Relation[],
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "GroupRelations",
        {
          "core_entity": core_entity,"relations": relations
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HyDE_rewrite(
      query: string,language: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "HyDE_rewrite",
        {
          "query": query,"language": language
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  MergeEntities(
      previous_entity: Entity,latest_entity: Entity,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "MergeEntities",
        {
          "previous_entity": previous_entity,"latest_entity": latest_entity
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeRelations(
      relationReferences: RelationReference[],entity_property: string,central_entity: Entity,language: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "SummarizeRelations",
        {
          "relationReferences": relationReferences,"entity_property": entity_property,"central_entity": central_entity,"language": language
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        false,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class HttpStreamRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  ExtractEntity(
      chunk_text: string,entity_type: string[],
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "ExtractEntity",
        {
          "chunk_text": chunk_text,"entity_type": entity_type
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEntityFromQuery(
      arg: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "ExtractEntityFromQuery",
        {
          "arg": arg
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractEntityLoop(
      chunk_text: string,entity_type: string[],already_identified_entities: Entity[],already_identified_relations: Relation[],
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "ExtractEntityLoop",
        {
          "chunk_text": chunk_text,"entity_type": entity_type,"already_identified_entities": already_identified_entities,"already_identified_relations": already_identified_relations
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  Extract_relations(
      content: string,entities: Entity[],language: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "Extract_relations",
        {
          "content": content,"entities": entities,"language": language
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  Extract_relations_Loop(
      content: string,language: string,already_identified_relations: Relation[],new_indentified_entities: Entity[],
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "Extract_relations_Loop",
        {
          "content": content,"language": language,"already_identified_relations": already_identified_relations,"new_indentified_entities": new_indentified_entities
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GenerateAnswer(
      query: string,documents: RetrievedDocument[],language: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "GenerateAnswer",
        {
          "query": query,"documents": documents,"language": language
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GroupRelations(
      core_entity: Entity,relations: Relation[],
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "GroupRelations",
        {
          "core_entity": core_entity,"relations": relations
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  HyDE_rewrite(
      query: string,language: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "HyDE_rewrite",
        {
          "query": query,"language": language
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  MergeEntities(
      previous_entity: Entity,latest_entity: Entity,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "MergeEntities",
        {
          "previous_entity": previous_entity,"latest_entity": latest_entity
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeRelations(
      relationReferences: RelationReference[],entity_property: string,central_entity: Entity,language: string,
      __baml_options__?: BamlCallOptions
  ): HTTPRequest {
    try {
      return this.runtime.buildRequestSync(
        "SummarizeRelations",
        {
          "relationReferences": relationReferences,"entity_property": entity_property,"central_entity": central_entity,"language": language
        },
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
        true,
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}