/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"

/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}


export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface Decision {
  response: string
  selected_task?: "Execute_RAG" | null | null
  
}

export interface EP_extract_result {
  reasoning: string
  subquestions: SubQuestion[]
  
}

export interface EPpair {
  entity: string
  property: string
  
}

export interface Entity {
  name: string
  description: string
  type: string
  aliases: string[]
  
}

export interface EntityExtractionExample {
  entity_type: string[]
  example_input: string
  extracted_entities: Entity[]
  
}

export interface EntityMatch {
  entity: string
  confidence: number
  
}

export interface EntityMatchResult {
  entity_name: string
  is_match: boolean
  matched_entity_name: string
  reasoning: string
  
}

export interface EntityWithRef {
  name: string
  description: string
  type: string
  aliases: string[]
  reference: number[]
  
}

export interface HyDE_rewrite_query {
  topic: string
  HyDE_answer: string
  
}

export interface HypothesizedProperty {
  hypothesis: string
  
}

export interface MissingEntityExtractionResult {
  extracted_entities: Entity[]
  reasoning: string
  
}

export interface Property {
  prop_name: string
  content: string
  
}

export interface PropertyGenerateRes {
  content: string
  referenceIndex: number[]
  
}

export interface Relation {
  source_entity: string
  target_entity: string
  relation: string
  
}

export interface RelationExtractResult {
  source_entity: number
  target_entity: number
  relation: string
  
}

export interface RelationGroup {
  group_name: string
  relation_index: number[]
  Reasoning: string
  
}

export interface RelationReference {
  relation: Relation
  doucment: string[]
  
}

export interface RetrievedDocument {
  content: string
  metadata: string
  
}

export interface RetrievedPropertyInfo {
  information: string
  sources: string[]
  
}

export interface SubQuestion {
  subquestion: string
  ep_pair: EPpair
  
}

export interface SummarizedProperty {
  summary: string
  
}

export interface Task {
  task_name: string
  task_description: string
  task_example_user_query: string[]
  
}

export interface UpdatedSummary {
  summary: string
  changes: string[]
  
}
