/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    EPpair: ClassViewer<'EPpair', "entity" | "property">;
    
    Entity: ClassViewer<'Entity', "name" | "description" | "type" | "aliases">;
    
    EntityExtractionExample: ClassViewer<'EntityExtractionExample', "entity_type" | "example_input" | "extracted_entities">;
    
    EntityMatch: ClassViewer<'EntityMatch', "entity" | "confidence">;
    
    EntityMatchResult: ClassViewer<'EntityMatchResult', "entity_name" | "is_match" | "matched_entity_name" | "reasoning">;
    
    EntityWithRef: ClassViewer<'EntityWithRef', "name" | "description" | "type" | "aliases" | "reference">;
    
    HyDE_rewrite_query: ClassViewer<'HyDE_rewrite_query', "HyDE_answer">;
    
    HypothesizedProperty: ClassViewer<'HypothesizedProperty', "hypothesis">;
    
    MissingEntityExtractionResult: ClassViewer<'MissingEntityExtractionResult', "extracted_entities" | "reasoning">;
    
    Property: ClassViewer<'Property', "prop_name" | "content">;
    
    PropertyGenerateRes: ClassViewer<'PropertyGenerateRes', "content" | "referenceIndex">;
    
    Relation: ClassViewer<'Relation', "source_entity" | "target_entity" | "relation">;
    
    RelationExtractResult: ClassViewer<'RelationExtractResult', "source_entity" | "target_entity" | "relation">;
    
    RelationGroup: ClassViewer<'RelationGroup', "group_name" | "relation_index" | "Reasoning">;
    
    RelationReference: ClassViewer<'RelationReference', "relation" | "doucment">;
    
    RetrievedDocument: ClassViewer<'RetrievedDocument', "content" | "metadata">;
    
    RetrievedPropertyInfo: ClassViewer<'RetrievedPropertyInfo', "information" | "sources">;
    
    SummarizedProperty: ClassViewer<'SummarizedProperty', "summary">;
    
    UpdatedSummary: ClassViewer<'UpdatedSummary', "summary" | "changes">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "EPpair","Entity","EntityExtractionExample","EntityMatch","EntityMatchResult","EntityWithRef","HyDE_rewrite_query","HypothesizedProperty","MissingEntityExtractionResult","Property","PropertyGenerateRes","Relation","RelationExtractResult","RelationGroup","RelationReference","RetrievedDocument","RetrievedPropertyInfo","SummarizedProperty","UpdatedSummary",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.EPpair = this.tb.classViewer("EPpair", [
          "entity","property",
        ]);
        
        this.Entity = this.tb.classViewer("Entity", [
          "name","description","type","aliases",
        ]);
        
        this.EntityExtractionExample = this.tb.classViewer("EntityExtractionExample", [
          "entity_type","example_input","extracted_entities",
        ]);
        
        this.EntityMatch = this.tb.classViewer("EntityMatch", [
          "entity","confidence",
        ]);
        
        this.EntityMatchResult = this.tb.classViewer("EntityMatchResult", [
          "entity_name","is_match","matched_entity_name","reasoning",
        ]);
        
        this.EntityWithRef = this.tb.classViewer("EntityWithRef", [
          "name","description","type","aliases","reference",
        ]);
        
        this.HyDE_rewrite_query = this.tb.classViewer("HyDE_rewrite_query", [
          "HyDE_answer",
        ]);
        
        this.HypothesizedProperty = this.tb.classViewer("HypothesizedProperty", [
          "hypothesis",
        ]);
        
        this.MissingEntityExtractionResult = this.tb.classViewer("MissingEntityExtractionResult", [
          "extracted_entities","reasoning",
        ]);
        
        this.Property = this.tb.classViewer("Property", [
          "prop_name","content",
        ]);
        
        this.PropertyGenerateRes = this.tb.classViewer("PropertyGenerateRes", [
          "content","referenceIndex",
        ]);
        
        this.Relation = this.tb.classViewer("Relation", [
          "source_entity","target_entity","relation",
        ]);
        
        this.RelationExtractResult = this.tb.classViewer("RelationExtractResult", [
          "source_entity","target_entity","relation",
        ]);
        
        this.RelationGroup = this.tb.classViewer("RelationGroup", [
          "group_name","relation_index","Reasoning",
        ]);
        
        this.RelationReference = this.tb.classViewer("RelationReference", [
          "relation","doucment",
        ]);
        
        this.RetrievedDocument = this.tb.classViewer("RetrievedDocument", [
          "content","metadata",
        ]);
        
        this.RetrievedPropertyInfo = this.tb.classViewer("RetrievedPropertyInfo", [
          "information","sources",
        ]);
        
        this.SummarizedProperty = this.tb.classViewer("SummarizedProperty", [
          "summary",
        ]);
        
        this.UpdatedSummary = this.tb.classViewer("UpdatedSummary", [
          "summary","changes",
        ]);
        
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}